export default [
  "function currentPackage(address user) view returns (uint256)",
  "function totalPackageValue(address user) view returns (uint256)",
  "function totalUsdtSpent(address user) view returns (uint256)",
  "function totalIncomeLimit(address user) view returns (uint256)",
  "function totalIncomeUsed(address user) view returns (uint256)",
  "function roiStartTime() view returns (uint256)",
  "function selfRoiPrincipal(address user) view returns (uint256)",
  "function selfRoiMaximum(address user) view returns (uint256)",
  "function selfRoiGenerated(address user) view returns (uint256)",
  "function pendingSelfRoi(address user) view returns (uint256)",
  "function rewardReleasedCount(address user,uint256 index) view returns (uint256)",
  "function pendingRewardIncome(address user,uint256 index) view returns (uint256)",
  "function carriedRewardIncome(address user,uint256 index) view returns (uint256)",
  "function rewardIncomeClaimedByIndex(address user,uint256 index) view returns (uint256)",
  "function rewardInstallmentsClaimedCount(address user,uint256 index) view returns (uint256)",
  "function rewardLastClaimAt(address user,uint256 index) view returns (uint256)",
  "function pendingPowerIncomeByLevel(address user,uint256 level) view returns (uint256)",
  "function carriedPowerIncomeByLevel(address user,uint256 level) view returns (uint256)",
  "function powerPayoutReleasedCountByLevel(address user,uint256 level) view returns (uint256)",
  "function powerIncomeClaimedByLevel(address user,uint256 level) view returns (uint256)",
  "function powerPayoutClaimedCountByLevel(address user,uint256 level) view returns (uint256)",
  "function getIncomeReady(address user,uint8 incomeType) view returns (uint256 readyAmount)",
  "function getPackageHistoryLength(address user) view returns (uint256)",
  "function getPackageHistoryAt(address user,uint256 index) view returns (uint256 amount,uint256 purchasedAt,uint256 deactivatedAt,uint256 roiGenerated,uint256 roiMaximum,bool active)",
  "function ROI_DAY() view returns (uint256)",
  "function roiStartTime() view returns (uint256)",
  "function getPowerDetails(address user) view returns ((uint256 activeLevel,uint256 achievedLevel,uint256 activatedAt,uint256 releasedCount,uint256 claimedCount,uint256 claimableAmount,uint256 totalClaimed,uint256 lastClaimAt,uint256 nextLevel,uint256 nextThreshold,uint256 nextQualifiedBusiness,uint256 nextRequiredBusiness,uint256 nextPayoutAt))",
  "function getPowerClaimHistoryLength(address user) view returns (uint256)",
  "function getPowerClaimHistoryAt(address user,uint256 index) view returns (uint256 level,uint256 payoutCount,uint256 amount,uint256 timestamp)",
  "function claimDirectIncome() returns (uint256 claimedAmount)",
  "function buyPackage(uint256 packageValue)",
  "function claimSelfRoi() returns (uint256 claimedAmount)",
  "function claimLevelRoi() returns (uint256 claimedAmount)",
  "function claimPowerIncome() returns (uint256 claimedAmount)",
  "function claimRewardIncome() returns (uint256 claimedAmount)",
  "event PackagePurchased(address indexed user, uint256 amount)",
  "event DirectIncomeClaimed(address indexed user, uint256 amount)",
  "event SelfRoiClaimed(address indexed user, uint256 amount)",
  "event LevelRoiClaimed(address indexed user, uint256 amount)",
  "event PowerIncomeClaimed(address indexed user, uint256 amount)",
  "event RewardIncomeClaimed(address indexed user, uint256 amount)"
];
