export default [
  "function users(address user) view returns (uint256 id,address referral,uint256 registeredAt,uint256 totalTeam,uint256 totalTeamDeposit,uint256 selfDeposit,uint256 totalTeamStakeToken,uint256 selfStakeToken,bool exists)",
  "function migrated(address user) view returns (bool)",
  "function isLevelOpen(address user,uint256 level) view returns (bool)",
  "function getAchievedRewardCount(address user) view returns (uint256)",
  "function getAchievedPowerLevel(address user) view returns (uint256)",
  "function powerAchievedAt(address user,uint256 level) view returns (uint256)",
  "function powerQualifiedBusiness(address user,uint256 level) view returns (uint256)",
  "function powerThreshold(uint256 level) view returns (uint256)",
  "function rewardQualifiedBusiness(address user,uint256 index) view returns (uint256)",
  "function rewardThreshold(uint256 index) view returns (uint256)",
  "function rewardAchievedAt(address user,uint256 index) view returns (uint256)",
  "function getPowerRewardSync(address user) view returns (uint256 powerLevel,uint256 rewardIndex,uint256 cursor,uint256 powerQualified,uint256 rewardQualified,bool active)",
  "function syncMyNextPowerReward(uint256 maxDirects) returns (uint256 processedDirects,uint256 totalDirects,bool completed,uint256 powerLevel,uint256 rewardIndex)",
  "function getLevelUsersLength(address upline,uint256 level) view returns (uint256)",
  "function getLevelUserAt(address upline,uint256 level,uint256 index) view returns (address)",
  "function legBusiness(address upline,address direct) view returns (uint256)",
  "function legacyLegBusiness(address upline,address direct) view returns (uint256)",
  "function legacyLevelRemaining(address user,uint256 level) view returns (uint256)",
  "function legacyLegsReady(address upline) view returns (bool)",
  "function legacyLegImportCursor(address upline) view returns (uint256)",
  "function importNextLegacyLegs(address upline,uint256 maxDirects) returns (uint256 processed,uint256 totalDirects,bool completed)",
  "function hasQualifiedPackage(address user) view returns (bool)",
  "function hasEverPackage(address user) view returns (bool)",
  "function legacyDirectCounted(address user) view returns (bool)"
];
